repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3
        args: [--target-version=py311]

  - repo: local
    hooks:
      - id: auto-stage-new-docs
        name: Auto stage new docs
        language: system
        entry: git add docs
        always_run: true

